### ISSUE TITLE
Merge changes from Glowkit 1.13-hack into 1.13

### ISSUE THREAD

**Issue by aramperes** [GlowstoneMC/Glowkit#23]
_Open to: **community**_
_Dependencies:_ #22 

---

The 1.13-hack has some changes required for our implementation in Glowstone, mostly related to block-data. Once the builds are working again, we can merge 1.13-hack into 1.13 (only the necessary patches) and use that for Glowstone's 1.13 branch.

**Comment by mastercoms** [comment]
Which patches exactly need to be taken? I don't see anything related to block data.

**Comment by aramperes** [comment]
Closing this since I can't remember what I did or where I put it... maybe I dreamed it. :)
